### ISSUE TITLE
11-25 Big OJT 会议内容 

### ISSUE THREAD

**Issue by Shanxiaolin** [Intern2020OJT/2020_Intern_Object#18]
### 上周回顾
- ise组课题的收尾工作，功能测试，小细节修改，最终发表。发表之后进入CT组，上周五与本周一做一些开始课题前的调研与学习。
### CT组研修
- 课题介绍
    -  具体的项目杨哥还没给出，介绍下CT组的课题大体的样子。
    -  实现github仓库里issues的图形化展示。
    -  部分展示的内容：每个人发表issues的数量图，所有issue的进度图。
    -  表现形式，以柱状图，曲线图等对一个项目的issues进行统计分析。
    -  涉及的方面有前后端开发，每个人都有前端后端的工作。
    -  大体上的工作介绍
        -  方案一：针对单个仓库issues的统计。
            - 登录页面，登录账号采用微信，github账号密码登录。（一个人做前后端的工作量）
            - 展示页面，罗列功能模块。（一个人做前后端的工作量）
            - 每个功能页面的具体实现。（一个人前端一个人后端工作量）
         - 方案二：多个仓库issues的综合统计
             - 展示页面，罗列功能模块。（一个人做前后端的工作量）
             - 每个功能页面的具体实现。（一个人前端一个人后端工作量）
- 目前的任务
    - 从上周四ise发表后，目前做的工作是CT项目之前的调研
    - [调研内容及分工](https://github.com/Intern2020OJT/CT_OBJ/projects/1#card-29674418)
    - 调研的内容不仅是上手前的知识储备，还要在11/26与杨哥要做一个综合的讨论，
决定出CSS部分使用哪种方法。
### Big Ojt本周的内容
 - 并行学习react的内容。
 - 储备react以及最新的hook知识，css扩展使用。

**Comment by Progyang** [comment]
### 补充
- 上周LT振东学长介绍了WebAppBot编程的相关内容,还有各种服务的使用方法
- 这周想尝试自定义一个Bot
